### ISSUE TITLE
GUI Consistency

### ISSUE THREAD

**Issue by otherotherjosh** [BIT-Studio-4/GTS#143]
## User Story
As a player, I want the visuals to be consistent, so that I don't rely on too much memorization to understand the game
As a dev, I want the UI system to be refactored, so that I can work with it more easily

## Issue
The inventory and store should both have their variables renamed to be more appropriate, there should also be more documentation where required. 
Additionally colours and alike things should be stored in one place like CSS variables. This will help expandability in the future, and also keep UI consistent in the present.

**Comment by KERERCVASD** [comment]
maybe this will help
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive
