### ISSUE TITLE
Brainstorm game ideas

### ISSUE THREAD

**Issue by otherotherjosh** [BIT-Studio-4/GTS#15]
On a whiteboard, paper or digital, write down all of the ideas we have. All of them.

**Comment by lolyay270** [comment]
please add brainstorming ideas to this [Microsoft Whiteboard](https://wbd.ms/share/v2/aHR0cHM6Ly93aGl0ZWJvYXJkLm1pY3Jvc29mdC5jb20vYXBpL3YxLjAvd2hpdGVib2FyZHMvcmVkZWVtLzgwZTYzM2RkNjhkNzRlNjVhODE5ZGJiNWFkOWYyZWU3X0JCQTcxNzYyLTEyRTAtNDJFMS1CMzI0LTVCMTMxRjQyNEUzRF84NjJjODk2Ni1lNmFjLTQwYTAtYWFkOS01YjQzNjljNzViYTA=)
